/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

/**
 *
 * @author sergio
 */
public class ClienteUI extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public ClienteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundPregunta = new javax.swing.JPanel();
        pregunta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblOpc1 = new javax.swing.JLabel();
        lblOpc2 = new javax.swing.JLabel();
        lblOpc3 = new javax.swing.JLabel();
        lblOpc4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(240, 244, 249));
        background.setMinimumSize(new java.awt.Dimension(509, 258));
        background.setPreferredSize(new java.awt.Dimension(800, 509));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPregunta.setBackground(new java.awt.Color(255, 255, 255));

        pregunta.setBackground(new java.awt.Color(255, 255, 255));
        pregunta.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("?");

        javax.swing.GroupLayout preguntaLayout = new javax.swing.GroupLayout(pregunta);
        pregunta.setLayout(preguntaLayout);
        preguntaLayout.setHorizontalGroup(
            preguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preguntaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        preguntaLayout.setVerticalGroup(
            preguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preguntaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPreguntaLayout = new javax.swing.GroupLayout(backgroundPregunta);
        backgroundPregunta.setLayout(backgroundPreguntaLayout);
        backgroundPreguntaLayout.setHorizontalGroup(
            backgroundPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
            .addGroup(backgroundPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundPreguntaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        backgroundPreguntaLayout.setVerticalGroup(
            backgroundPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
            .addGroup(backgroundPreguntaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backgroundPreguntaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        background.add(backgroundPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 810, -1));

        lblOpc1.setBackground(new java.awt.Color(215, 26, 57));
        lblOpc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trianguloGDE.png"))); // NOI18N
        lblOpc1.setText("opc1");
        lblOpc1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpc1.setOpaque(true);
        background.add(lblOpc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, 80));

        lblOpc2.setBackground(new java.awt.Color(18, 96, 190));
        lblOpc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rombo.png"))); // NOI18N
        lblOpc2.setText("opc2");
        lblOpc2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpc2.setOpaque(true);
        background.add(lblOpc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 380, 80));

        lblOpc3.setBackground(new java.awt.Color(199, 146, 0));
        lblOpc3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/circulo.png"))); // NOI18N
        lblOpc3.setText("opc3");
        lblOpc3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpc3.setOpaque(true);
        background.add(lblOpc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 380, 80));

        lblOpc4.setBackground(new java.awt.Color(35, 126, 11));
        lblOpc4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cuadrado.png"))); // NOI18N
        lblOpc4.setText("opc4");
        lblOpc4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpc4.setOpaque(true);
        background.add(lblOpc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 380, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundPregunta;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblOpc1;
    private javax.swing.JLabel lblOpc2;
    private javax.swing.JLabel lblOpc3;
    private javax.swing.JLabel lblOpc4;
    private javax.swing.JPanel pregunta;
    // End of variables declaration//GEN-END:variables
}
